CREATE  TABLE reviews(
id VARCHAR(255) PRIMARY KEY NOT NULL,
reviewDescription VARCHAR (255) NOT NULL DEFAULT 'empty',
userID VARCHAR (255)  FOREIGN KEY REFERENCES users(id) DEFAULT 'empty' NOT NULL,
tourID VARCHAR (255) FOREIGN KEY REFERENCES tours(id) DEFAULT 'empty' NOT NULL
)
